### PR TITLE
Use `utils.functions.listAll()`

### PR DESCRIPTION
**Pull request by ehmicky**
A utility method `utils.functions.list()` (documentation [here](https://github.com/netlify/build/blob/master/packages/functions-utils/README.md#list)) is available to list the Netlify Function main files in a project.

This allows removing some code in this plugin. This also fixes some bugs due to the rather intricate logic involved in figuring out Netlify Function main files. For example, the plugin currently does not work when no `functions` directory was set.

If this PR looks good to you, would it be possible for you to give it a quick test in production to make sure everything works? Thanks!

### CODE REVIEW

**Comment by bencao** [comment]
One quick question about the utils.functions.list API.

If my functions folder looks like this:

```
functions
├── lib
│   └── auth.js
├── users.js
└── projects.js
```

users.js can `require("./lib/auth.js")`, and in auth.js there's a reference to `process.env.TOKEN`

would `lib/auth.js` be included in the `utils.functions.list` response?

according to my local test, only `users.js` and `projects.js` will be reported.

**Comment by ehmicky** [comment]
Oh, you're right, `utils.functions.list()` only list the Function main files, not the files they `require()`. I realize that this plugin needs to inline also the required files, so this PR will not work.

The problem is that the logic to find required files in Netlify Functions is [rather intricate](https://github.com/netlify/zip-it-and-ship-it/blob/master/src/dependencies.js). There are many files to watch for. Ideally, `utils.functions.list()` should return not only the entry point, but also the list of required files. What do you think?

**Comment by ehmicky** [comment]
Hi @bencao,

I have added a new utility `utils.functions.listAll()` (documentation [here](https://github.com/netlify/build/blob/master/packages/functions-utils/README.md#listall)) to list both the Netlify Function main file and its required files. This should take care of the problem you mentioned.

Could you please give it a try and confirm this is working as intended? Thanks!

**Comment by bencao** [comment]
@ehmicky Sorry for the late reply. According to my test, `utils.functions.listAll` result still did not include source files in sub folders. My test case is a functions folder with the following files:

```
.
├── lib
│   └── auth.js
├── project.js
└── users.js
```

lib/auth.js is missing.

**Comment by ehmicky** [comment]
If `users.js` has a `require('./lib/auth.js')`, both `users.js` and `lib/auth.js` should be returned by `utils.functions.listAll()`.

`utils.functions.listAll()` is using the same logic used by Netlify to bundle Functions. If a file is not returned by `utils.functions.listAll()`, it is probably not bundled in the Function.

**Comment by dac09** [comment]
Hi @ehmicky just tried your branch, but it looks like it also picks up node_modules, just FYI

**Comment by ehmicky** [comment]
@dac09 Nice catch! I just fixed it in 3db293d2023fc95d0c9b8f527392faca24619788.

**Comment by dac09** [comment]
I also think it picked up a non-js file. 

```
Error: Failed to inline function files due to the following error: /opt/build/repo/node_modules/@babel/runtime-corejs3/LICENSE: Unexpected token, expected ";" (1:4)

    1 | MIT License | ^ 2 | 3 | Copyright (c) 2014-present Sebastian McKenzie and other contributors 4 | 
```
But the node_modules change should take care of this

**Comment by ehmicky** [comment]
Nice catch too! I just created a PR at https://github.com/netlify/zip-it-and-ship-it/pull/173 to fix it.

However, as you point out, this bug only happens inside `node_modules`, so should not impact this PR anymore.

**Comment by dac09** [comment]
@ehmicky it'd be nice if you guys (i.e. netlify) could add a way of testing these plugins locally by mocking netlify's runtime env in jest. It'd be nice to not have to run builds on the server every time, or to write mocks for netlify's build runtime.

**Comment by ehmicky** [comment]
You can run Build plugins locally using the Netlify CLI command `netlify build`. This tries to emulate Netlify's runtime environment as much as possible (including environment variables). 
Note also that Build plugins can be either a npm package or a local directory.

When it comes to integrating with specific tools such as Jest (or others), I think we would like to gather additional feedback from the setup described above (Netlify CLI `netlify build`) before adding specific integrations to those tools.

**Comment by ehmicky** [comment]
I have rebased the PR onto the latest `master`.

I have also manually tested it, and I can confirm required files like `lib/auth.js` are included, but Node.js modules are not. :+1:

**Comment by dac09** [comment]
> I have also manually tested it, and I can confirm required files like lib/auth.js are included, but Node.js modules are not. 👍
Awesome, this makes the plugin cater to a lot more usecases!

**Review by bencao — APPROVED** [review]
Thanks. Looks good to me and passed for local test.

**Comment by ehmicky** [comment]
Thanks @bencao!
Would it be possible to update the version in the Netlify UI plugins list ([`netlify/plugins`](https://github.com/netlify/plugins))? Thanks!

**Pull request merged**
